# Generated by Django 3.0.6 on 2020-06-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200616_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
