# Generated by Django 3.0.6 on 2020-07-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200704_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(default='Point of View', max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
